// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRS.Data;

#nullable disable

namespace TRS.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240621025501_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TRS.Models.JobClass", b =>
                {
                    b.Property<long>("RecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordNo"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByComputerUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobClassDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByComputerUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScheduleTrainingCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RecordNo");

                    b.HasIndex("ProgramCode");

                    b.HasIndex("ScheduleTrainingCode");

                    b.ToTable("mJobClass", "TRS");
                });

            modelBuilder.Entity("TRS.Models.TrainingCourse", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByComputerUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByComputerUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PostTestTotalScore")
                        .HasColumnType("bigint");

                    b.Property<long?>("PreTestTotalScore")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordNo"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("WithEvaluation")
                        .HasColumnType("bit");

                    b.Property<bool>("WithPostTest")
                        .HasColumnType("bit");

                    b.Property<bool>("WithPreTest")
                        .HasColumnType("bit");

                    b.HasKey("CourseCode");

                    b.HasIndex("ProgramCode");

                    b.ToTable("mTrainingCourse", "TRS");
                });

            modelBuilder.Entity("TRS.Models.TrainingProgram", b =>
                {
                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByComputerUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByComputerUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordNo"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProgramCode");

                    b.ToTable("mTrainingProgram", "TRS");
                });

            modelBuilder.Entity("TRS.Models.TrainingSchedule", b =>
                {
                    b.Property<string>("TrainingCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClassSize")
                        .HasColumnType("int");

                    b.Property<string>("CostPerHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByComputerUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MinimumParticipants")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByComputerUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordNo"));

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceSpeaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingCode");

                    b.HasIndex("CourseCode");

                    b.HasIndex("ProgramCode");

                    b.ToTable("tTrainingSchedule", "TRS");
                });

            modelBuilder.Entity("TRS.Models.UserLogs", b =>
                {
                    b.Property<long>("RecordNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordNo"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByComputerUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordNo");

                    b.ToTable("tUserLogs", "TRS");
                });

            modelBuilder.Entity("TRS.Models.JobClass", b =>
                {
                    b.HasOne("TRS.Models.TrainingProgram", "Program")
                        .WithMany("JobClasses")
                        .HasForeignKey("ProgramCode");

                    b.HasOne("TRS.Models.TrainingSchedule", "Schedule")
                        .WithMany("AdditionalJobClasses")
                        .HasForeignKey("ScheduleTrainingCode");

                    b.Navigation("Program");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TRS.Models.TrainingCourse", b =>
                {
                    b.HasOne("TRS.Models.TrainingProgram", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("TRS.Models.TrainingSchedule", b =>
                {
                    b.HasOne("TRS.Models.TrainingCourse", "Course")
                        .WithMany()
                        .HasForeignKey("CourseCode");

                    b.HasOne("TRS.Models.TrainingProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramCode");

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("TRS.Models.TrainingProgram", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("JobClasses");
                });

            modelBuilder.Entity("TRS.Models.TrainingSchedule", b =>
                {
                    b.Navigation("AdditionalJobClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
